parameters:
    support_tools.info_collectors.doctrine_database.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\DoctrineDatabaseSystemInfoCollector
    support_tools.info_collectors.ezc_hardware.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.info_collectors.composer.lock_file.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\JsonComposerLockSystemInfoCollector
    support_tools.info_collectors.php.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcPhpSystemInfoCollector

services:
    support_tools.info_collectors.doctrine_database:
        class: %support_tools.info_collectors.doctrine_database.class%
        arguments:
            - @database_connection

    support_tools.info_collectors.ezc_hardware:
        class: %support_tools.info_collectors.ezc_hardware.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc_system_info

    support_tools.info_collectors.composer.lock_file:
        class: %support_tools.info_collectors.composer.lock_file.class%
        arguments:
            - "%kernel.root_dir%/../"

    support_tools.info_collectors.php:
        class: %support_tools.info_collectors.php.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc_system_info

    support_tools.info_collector.system_info.ezc_system_info:
        class: ezcSystemInfo
        factory: [EzSystems\EzSupportToolsBundle\SystemInfo\EzcSystemInfoFactory, buildEzcSystemInfo]
